create table if not exists public.products (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, name text not null, description text default '', price numeric(10,2) not null default 0, stock integer not null default 0, image_url text default '', available boolean default true, created_at timestamptz default now());
create table if not exists public.orders (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, order_number text, customer_email text, customer_address text, shipping_method text, shipping_price numeric(10,2) default 0, total numeric(10,2) default 0, status text default 'Nuovo', created_at timestamptz default now());
create table if not exists public.coupons (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, name text not null, code text not null, percent_off numeric(5,2) not null default 0, active boolean default true, created_at timestamptz default now(), unique(owner_id,code));
create table if not exists public.store_settings (owner_id uuid primary key references auth.users(id) on delete cascade, store_name text default 'Il Gatto di Cruci', contact_email text, phone text, shipping_address text, updated_at timestamptz default now());
alter table public.products enable row level security; alter table public.orders enable row level security; alter table public.coupons enable row level security; alter table public.store_settings enable row level security;
create policy "owners manage products" on public.products for all using (owner_id=auth.uid()) with check (owner_id=auth.uid());
create policy "owners manage orders" on public.orders for all using (owner_id=auth.uid()) with check (owner_id=auth.uid());
create policy "owners manage coupons" on public.coupons for all using (owner_id=auth.uid()) with check (owner_id=auth.uid());
create policy "owners manage settings" on public.store_settings for all using (owner_id=auth.uid()) with check (owner_id=auth.uid());
