services:
  - type: web
    name: il-gatto-di-cruci
    runtime: static
    branch: main
    autoDeployTrigger: commit
    buildCommand: ""
    staticPublishPath: .
    headers:
      - path: /admin
        name: Cache-Control
        value: no-store
      - path: /admin/*
        name: Cache-Control
        value: no-store
