const productVariants={
  'Orecchini Singoli (vari)':['⚫ Orecchino – Ossidiana Oro','Orecchino – Fluorite','Orecchino – Avventurina & Quarzo Rosa'],
  'Pendolo in pietra naturale (varie)':['rubino con zoisite','quarzo rosa','lepidolite','angelite'],
  'Pendenti a Goccia Vari (catenina acciaio inclusa)':['quarzo rosa bagno argento','ametista','ametista bagno argento','quarzo tormalinato bagno argento'],
  'Ciondoli Tormalina Varie (catenina acciaio inclusa)':['Punta','Cabochon'],
  'Bracciali Chips Piete Naturali (vari) con Elastico':['Giada','Lepidolite','Ossidiana','Ametista','Amazonite'],
  'Anelli Regolabili Vari':['Turchese','Ossidiana','Citrino','Labradorite']
};
document.addEventListener('click',event=>{const trigger=event.target.closest('[data-detail]'),card=trigger?.closest('.product-card'),title=card?.querySelector('.product-name')?.textContent.trim(),variants=productVariants[title];if(!variants)return;event.stopImmediatePropagation();event.preventDefault();const dialog=document.querySelector('#product-dialog'),detail=document.querySelector('#product-detail'),image=card.querySelector('img').src,id=card.querySelector('.add').dataset.id,price=card.querySelector('.product-price').textContent;detail.innerHTML=`<div class="detail"><div class="detail-image"><img src="${image}" alt="${title}"></div><div class="detail-copy"><p class="eyebrow">Varianti disponibili</p><h2>${title}</h2><p class="detail-description">Scegli la pietra o la finitura che preferisci prima di aggiungere l’articolo alla borsa.</p><label>Variante<select id="variant-choice" class="variant-select">${variants.map(v=>`<option>${v}</option>`).join('')}</select></label><div class="detail-info"><span class="availability">Disponibile</span><strong class="detail-price">${price}</strong></div><button class="button" id="variant-add">Aggiungi alla borsa</button></div></div>`;dialog.showModal();document.querySelector('#variant-add').onclick=()=>{const variant=document.querySelector('#variant-choice').value;card.querySelector('.add').click();setTimeout(()=>{const cart=JSON.parse(localStorage.getItem('cruci-cart')||'[]'),row=cart.find(x=>String(x.id)===String(id));if(row){row.variant=variant;localStorage.setItem('cruci-cart',JSON.stringify(cart))}dialog.close()},0)}},true);
