import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const supabase=createClient('https://waeiuyzteusfsajmzbj.supabase.co','sb_publishable_0zscL8lzkUbSgDHxs0lfIw_Pu6XVMJV');
const $=s=>document.querySelector(s), navItems=[['home','⌂','Home'],['links','⌁','Link'],['products','◇','Prodotti'],['orders','▣','Ordini'],['customers','♧','Clienti'],['coupons','✿','Coupon'],['returns','↩','Resi'],['payments','▦','Incassi'],['settings','⚙','Impostazioni']];let user,products=[];
function euro(v){return new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(v||0)}function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function auth(){const{data:{session}}=await supabase.auth.getSession();if(session){user=session.user;$('#auth-view').hidden=true;$('#app').hidden=false;renderNav();go('home')}}
$('#auth-form').onsubmit=async e=>{e.preventDefault();const{error}=await supabase.auth.signInWithPassword({email:$('#auth-email').value,password:$('#auth-password').value});$('#auth-message').textContent=error?.message||'';if(!error)auth()};$('#signup').onclick=async()=>{const{error}=await supabase.auth.signUp({email:$('#auth-email').value,password:$('#auth-password').value});$('#auth-message').textContent=error?'Errore: '+error.message:'Controlla la tua email per confermare l’account.'};$('#logout').onclick=async()=>{await supabase.auth.signOut();location.reload()};
function renderNav(){ $('#nav').innerHTML=navItems.map(([id,icon,label])=>`<button data-go="${id}">${icon}&nbsp;&nbsp;${label}</button>`).join('');$('#nav').onclick=e=>e.target.dataset.go&&go(e.target.dataset.go)}
async function getProducts(){const{data,error}=await supabase.from('products').select('*').order('created_at',{ascending:false});if(error)throw error;products=data||[]}
async function go(page){document.querySelectorAll('[data-go]').forEach(b=>b.classList.toggle('active',b.dataset.go===page));try{if(page==='products'||page==='home'||page==='links')await getProducts();if(page==='home')home();else if(page==='products')productPage();else if(page==='orders')orders();else if(page==='customers')customers();else if(page==='coupons')coupons();else if(page==='settings')settings();else simple(page)}catch(e){$('#content').innerHTML=`<h1>Errore</h1><div class="card">${esc(e.message)}<br><br>Prima esegui lo script SQL <code>supabase/schema.sql</code> nel SQL Editor di Supabase.</div>`}}
function home(){const available=products.filter(p=>p.available).length;$('#content').innerHTML=`<div class="top"><h1>Home</h1><span class="muted">Ultimi 7 giorni</span></div><section class="stats"><div class="stat">Vendite<b>${euro(0)}</b></div><div class="stat">Ordini<b>0</b></div><div class="stat">Prodotti attivi<b>${available}</b></div><div class="stat">Articoli<b>${products.length}</b></div></section><h2>Link</h2><div class="list"><div class="row"><span>☾</span><div><strong>Il Gatto di Cruci</strong><p>${products.length} prodotti pubblicati</p></div><strong>${euro(0)}</strong></div></div>`}
function productPage(){$('#content').innerHTML=`<div class="top"><h1>Prodotti</h1><button id="new">＋ Nuovo prodotto</button></div><input class="search" id="search" placeholder="⌕  Cerca..."><div class="list" id="list"></div>`;const draw=()=>{$('#list').innerHTML=products.filter(p=>p.name.toLowerCase().includes($('#search').value.toLowerCase())).map(p=>`<div class="row"><img src="${esc(p.image_url||'')}" alt=""><div><strong>${esc(p.name)}</strong><p>Quantità: ${p.stock??0} ${p.available?'':'· Esaurito'}</p></div><strong>${euro(p.price)}</strong></div>`).join('')||'<p class="empty">Nessun prodotto. Creane uno per iniziare.</p>'};draw();$('#search').oninput=draw;$('#new').onclick=productForm}
function productForm(){const box=document.createElement('div');box.className='modal';box.innerHTML=`<form><div class="top"><h2>Nuovo prodotto</h2><button type="button" class="ghost" id="close">×</button></div><div class="form-grid"><label class="wide">Nome<input name="name" required></label><label>Prezzo €<input name="price" type="number" min="0" step=".01" required></label><label>Quantità<input name="stock" type="number" min="0" value="1"></label><label class="wide">URL foto<input name="image_url" type="url"></label><label class="wide">Descrizione<textarea name="description" rows="4"></textarea></label><label><input name="available" type="checkbox" checked> Disponibile</label></div><div class="actions"><button type="button" class="ghost" id="cancel">Annulla</button><button>Salva</button></div></form>`;document.body.append(box);box.querySelectorAll('#close,#cancel').forEach(x=>x.onclick=()=>box.remove());box.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),payload={owner_id:user.id,name:f.get('name'),price:Number(f.get('price')),stock:Number(f.get('stock')),image_url:f.get('image_url'),description:f.get('description'),available:f.get('available')==='on'};const{error}=await supabase.from('products').insert(payload);if(error)return alert(error.message);box.remove();go('products')}}
async function orders(){const{data,error}=await supabase.from('orders').select('*').order('created_at',{ascending:false});if(error)throw error;$('#content').innerHTML=`<h1>Ordini</h1><input class="search" placeholder="⌕ Cerca..."><div class="list">${data?.map(o=>`<div class="row"><span class="status">✓</span><div><strong>Ordine #${esc(o.order_number||o.id.slice(0,8))}</strong><p>${esc(o.customer_email||'Cliente')} · ${esc(o.status||'Nuovo')}</p></div><strong>${euro(o.total)}</strong></div>`).join('')||'<p class="empty">Ancora nessun ordine.</p>'}</div>`}
async function customers(){const{data,error}=await supabase.from('orders').select('customer_email').not('customer_email','is',null);if(error)throw error;const counts={};(data||[]).forEach(x=>counts[x.customer_email]=(counts[x.customer_email]||0)+1);$('#content').innerHTML=`<h1>Clienti</h1><input class="search" placeholder="⌕ Cerca..."><div class="list">${Object.entries(counts).map(([email,n])=>`<div class="row"><span>●</span><div><strong>${esc(email)}</strong><p>${n} ordini</p></div><span>›</span></div>`).join('')||'<p class="empty">I clienti appariranno con i primi ordini.</p>'}</div>`}
async function coupons(){const{data,error}=await supabase.from('coupons').select('*').order('created_at',{ascending:false});if(error)throw error;$('#content').innerHTML=`<div class="top"><h1>Coupon</h1><button id="newcoupon">＋ Nuovo coupon</button></div><div class="list">${data?.map(c=>`<div class="row"><span>✿</span><div><strong>${esc(c.name)}</strong><p>Sconto ${c.percent_off}%</p></div><strong>${esc(c.code)}</strong></div>`).join('')||'<p class="empty">Nessun coupon.</p>'}</div>`;$('#newcoupon').onclick=async()=>{const name=prompt('Nome coupon'),code=prompt('Codice'),percent=prompt('Sconto percentuale');if(name&&code&&percent){const{error}=await supabase.from('coupons').insert({owner_id:user.id,name,code,percent_off:Number(percent)});if(error)alert(error.message);go('coupons')}}}
function simple(page){const labels={links:'Link di vendita',returns:'Resi',payments:'Incassi'};$('#content').innerHTML=`<h1>${labels[page]}</h1><div class="card">${page==='returns'?'<div class="notice"><h2>Gestisci i resi</h2><p>Qui potrai approvare richieste di reso e gestire rimborsi.</p></div>':page==='payments'?'<h2>Non hai ancora pagamenti</h2><p>Qui vedrai gli incassi in arrivo e quelli già trasferiti.</p>':'<h2>Il Gatto di Cruci</h2><p>Il link pubblico del tuo catalogo è pronto.</p>'}</div>`}
async function settings(){const{data,error}=await supabase.from('store_settings').select('*').maybeSingle();if(error)throw error;const s=data||{};$('#content').innerHTML=`<h1>Impostazioni</h1><form class="card" id="settings"><div class="form-grid"><label class="wide">Nome del negozio<input name="store_name" value="${esc(s.store_name||'Il Gatto di Cruci')}"></label><label>Email ordini<input name="contact_email" type="email" value="${esc(s.contact_email||'')}"></label><label>Telefono<input name="phone" value="${esc(s.phone||'')}"></label><label class="wide">Indirizzo di spedizione<textarea name="shipping_address">${esc(s.shipping_address||'')}</textarea></label></div><div class="actions"><button>Salva modifiche</button></div></form>`;$('#settings').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),payload={owner_id:user.id,store_name:f.get('store_name'),contact_email:f.get('contact_email'),phone:f.get('phone'),shipping_address:f.get('shipping_address')};const{error}=await supabase.from('store_settings').upsert(payload,{onConflict:'owner_id'});if(error)alert(error.message);else alert('Salvato')}}
auth();
